In [ ]:
#23070521113_VedantRajekar
# Install dependencies as needed:
# This command installs kagglehub along with pandas support.
!pip install kagglehub[pandas-datasets]

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.13/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (26.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (2.2.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

In [ ]:
import kagglehub
import pandas as pd
import os

# The dataset 'kartik2112/fraud-detection' contains 'creditcard.csv'
dataset_handle = "kartik2112/fraud-detection"
file_name_in_dataset = "fraudTrain.csv" # Corrected file name to fraudTrain.csv

# Load the dataset using KaggleHub
try:
    # Use dataset_download to get the local path to the downloaded dataset directory
    # This will download and unzip the dataset (if it's a zip).
    download_dir = kagglehub.dataset_download(handle=dataset_handle)
    print(f"Dataset downloaded to directory: {download_dir}")

    # Construct the full path to the fraudTrain.csv file
    full_file_path = os.path.join(download_dir, file_name_in_dataset)

    # Check if the file actually exists at the constructed path
    if not os.path.exists(full_file_path):
        print(f"Error: Expected file not found at {full_file_path}")
        print(f"Files found in download directory: {os.listdir(download_dir)}")
        df = None
    else:
        # Now, load the CSV file into a pandas DataFrame
        df = pd.read_csv(full_file_path)
        print(f"Dataset '{file_name_in_dataset}' loaded into DataFrame successfully from '{full_file_path}'.")

        # Display first 5 records as a sanity check
        print("\nFirst 5 records:")
        display(df.head())

except Exception as e:
    print(f"Error loading dataset from KaggleHub: {e}")
    print("Please ensure you have network access and the dataset handle/file name are correct.")
    df = None

Using Colab cache for faster access to the 'fraud-detection' dataset.
Dataset downloaded to directory: /kaggle/input/fraud-detection
Dataset 'fraudTrain.csv' loaded into DataFrame successfully from '/kaggle/input/fraud-detection/fraudTrain.csv'.

First 5 records:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

### 2. Initial Data Exploration

Let's get a first look at the data, including its structure and check for class imbalance.

In [ ]:
if df is not None:
    # Display the first 5 rows of the dataset
    print("First 5 rows of the dataset:")
    display(df.head())

    # Display concise summary of the DataFrame
    print("\nDataFrame Info:")
    df.info()

    # Check the distribution of the 'is_fraud' target variable
    print("\nClass Distribution (is_fraud):")
    display(df['is_fraud'].value_counts())
    display(df['is_fraud'].value_counts(normalize=True) * 100)
else:
    print("DataFrame 'df' is not available. Please ensure the dataset was loaded successfully.")

First 5 rows of the dataset:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

Class Distribution (is_fraud):

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

is_fraud
0    99.421135
1     0.578865
Name: proportion, dtype: float64

### 3. Data Preprocessing and Feature Engineering

We need to prepare the data for the deep neural network. This involves:
1.  **Dropping irrelevant columns**: Removing identifiers or columns that don't add predictive power.
2.  **Feature Engineering**: Extracting useful information from existing columns (e.g., time features).
3.  **Handling Categorical Features**: Converting categorical data into a numerical format suitable for neural networks.
4.  **Scaling Numerical Features**: Normalizing numerical features to a similar range to help the neural network converge faster.

In [ ]:
import numpy as np

# Drop irrelevant columns
columns_to_drop = [
    'Unnamed: 0', # Likely an artifact/index column
    'cc_num',     # Credit card number (identifier, sensitive, high cardinality)
    'first',      # First name (identifier)
    'last',       # Last name (identifier)
    'street',     # Street address (high cardinality, location already covered by lat/long)
    'trans_num',  # Transaction number (identifier)
    'dob',        # Date of birth (can lead to privacy concerns and high cardinality if not engineered carefully, simpler to drop for initial model)
    'city',       # City (high cardinality, consider dropping for initial model)
    'state'       # State (high cardinality, consider dropping for initial model)
]

# Check if columns exist before dropping
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]

if existing_columns_to_drop:
    df_processed = df.drop(columns=existing_columns_to_drop)
    print(f"Dropped columns: {existing_columns_to_drop}")
else:
    df_processed = df.copy()
    print("No specified columns to drop were found in the DataFrame.")

# Convert 'trans_date_trans_time' to datetime objects and extract features
df_processed['trans_date_trans_time'] = pd.to_datetime(df_processed['trans_date_trans_time'])

df_processed['hour'] = df_processed['trans_date_trans_time'].dt.hour
df_processed['day'] = df_processed['trans_date_trans_time'].dt.day
df_processed['month'] = df_processed['trans_date_trans_time'].dt.month
df_processed['year'] = df_processed['trans_date_trans_time'].dt.year
df_processed['day_of_week'] = df_processed['trans_date_trans_time'].dt.dayofweek
df_processed['is_weekend'] = (df_processed['trans_date_trans_time'].dt.dayofweek >= 5).astype(int) # Saturday=5, Sunday=6

# Drop the original 'trans_date_trans_time' and 'unix_time' after extraction
df_processed = df_processed.drop(columns=['trans_date_trans_time', 'unix_time'])

print("\nDataFrame after initial drops and feature engineering:")
display(df_processed.head())
df_processed.info()

Dropped columns: ['Unnamed: 0', 'cc_num', 'first', 'last', 'street', 'trans_num', 'dob', 'city', 'state']

DataFrame after initial drops and feature engineering:

,merchant,category,amt,gender,zip,lat,long,city_pop,job,merch_lat,merch_long,is_fraud,hour,day,month,year,day_of_week,is_weekend
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,28654,36.0788,-81.1781,3495,"Psychologist, counselling",36.011293,-82.048315,0,0,1,1,2019,1,0
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,99160,48.8878,-118.2105,149,Special educational needs teacher,49.159047,-118.186462,0,0,1,1,2019,1,0
2,fraud_Lind-Buckridge,entertainment,220.11,M,83252,42.1808,-112.2620,4154,Nature conservation officer,43.150704,-112.154481,0,0,1,1,2019,1,0
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,59632,46.2306,-112.1138,1939,Patent attorney,47.034331,-112.561071,0,0,1,1,2019,1,0
4,fraud_Keeling-Crist,misc_pos,41.96,M,24433,38.4207,-79.4629,99,Dance movement psychotherapist,38.674999,-78.632459,0,0,1,1,2019,1,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 18 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   merchant     1296675 non-null  object
 1   category     1296675 non-null  object
 2   amt          1296675 non-null  float64
 3   gender       1296675 non-null  object
 4   zip          1296675 non-null  int64
 5   lat          1296675 non-null  float64
 6   long         1296675 non-null  float64
 7   city_pop     1296675 non-null  int64
 8   job          1296675 non-null  object
 9   merch_lat    1296675 non-null  float64
 10  merch_long   1296675 non-null  float64
 11  is_fraud     1296675 non-null  int64
 12  hour         1296675 non-null  int32
 13  day          1296675 non-null  int32
 14  month        1296675 non-null  int32
 15  year         1296675 non-null  int32
 16  day_of_week  1296675 non-null  int32
 17  is_weekend   1296675 non-null  int64
dtypes: float64(5), int32(5), int64(4), object(4)
memory usage: 153.3+ MB

Next, we'll handle categorical features using one-hot encoding and scale the numerical features. This is crucial for deep learning models.

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify numerical and categorical features
numerical_features = df_processed.select_dtypes(include=np.number).columns.tolist()
categorical_features = df_processed.select_dtypes(include='object').columns.tolist()

# Remove the target variable 'is_fraud' from numerical features list
if 'is_fraud' in numerical_features:
    numerical_features.remove('is_fraud')

print(f"Numerical features: {numerical_features}")
print(f"Categorical features: {categorical_features}")

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore') # handle_unknown='ignore' for unseen categories in test set

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='passthrough' # Keep any other columns (e.g., 'is_fraud' which was not in numerical or categorical list)
)

# Apply the preprocessing steps
# Temporarily separate target variable before applying preprocessor
X = df_processed.drop(columns=['is_fraud'])
y = df_processed['is_fraud']

# Fit and transform the features
X_processed = preprocessor.fit_transform(X)

# Convert the processed features back to a DataFrame for easier handling, if needed
# This step can be memory intensive if many new columns are created by OneHotEncoder
# For DNN, often directly use the numpy array X_processed
print("\nShape of processed features (X_processed):", X_processed.shape)
print("Shape of target variable (y):", y.shape)

# To see column names after one-hot encoding, you can reconstruct DataFrame (optional)
# feature_names = numerical_features + list(preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features))
# X_processed_df = pd.DataFrame(X_processed, columns=feature_names)
# display(X_processed_df.head())

Numerical features: ['amt', 'zip', 'lat', 'long', 'city_pop', 'merch_lat', 'merch_long', 'hour', 'day', 'month', 'year', 'day_of_week', 'is_weekend']
Categorical features: ['merchant', 'category', 'gender', 'job']

Shape of processed features (X_processed): (1296675, 1216)
Shape of target variable (y): (1296675,)

### 4. Splitting Data and Applying SMOTE

Before training our deep neural network, we need to:
1.  **Split the data**: Separate the dataset into training and testing sets.
2.  **Apply SMOTE**: Use SMOTE (Synthetic Minority Over-sampling Technique) on the *training data only* to address the class imbalance. This will generate synthetic samples for the minority class, helping the model learn better.

In [ ]:
# Install imbalanced-learn for SMOTE
!pip install imbalanced-learn

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
# Stratify by 'y' to maintain the same class distribution in both sets
# Use a test size of 20% (0.2), which is common
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42, stratify=y)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\nClass distribution in y_train before SMOTE:")
display(y_train.value_counts())
display(y_train.value_counts(normalize=True) * 100)

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.13/dist-packages (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (2.1.3)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (3.6.0)
Shape of X_train: (1037340, 1216)
Shape of X_test: (259335, 1216)
Shape of y_train: (1037340,)
Shape of y_test: (259335,)

Class distribution in y_train before SMOTE:

is_fraud
0    1031335
1       6005
Name: count, dtype: int64

is_fraud
0    99.421116
1     0.578884
Name: proportion, dtype: float64

In [ ]:
from imblearn.over_sampling import SMOTE

print("Applying SMOTE to the training data...")

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("SMOTE application complete.")
print(f"Shape of X_train_resampled: {X_train_resampled.shape}")
print(f"Shape of y_train_resampled: {y_train_resampled.shape}")

print("\nClass distribution in y_train after SMOTE:")
display(y_train_resampled.value_counts())
display(y_train_resampled.value_counts(normalize=True) * 100)

Applying SMOTE to the training data...
SMOTE application complete.
Shape of X_train_resampled: (2062670, 1216)
Shape of y_train_resampled: (2062670,)

Class distribution in y_train after SMOTE:

is_fraud
0    1031335
1    1031335
Name: count, dtype: int64

is_fraud
0    50.0
1    50.0
Name: proportion, dtype: float64

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the Deep Neural Network architecture
model = keras.Sequential([
    layers.Input(shape=(X_train_resampled.shape[1],)), # Input layer matching the number of features
    layers.Dense(256, activation='relu'), # First hidden layer with 256 neurons and ReLU activation
    layers.BatchNormalization(),          # Batch Normalization for stability and faster training
    layers.Dropout(0.3),                  # Dropout for regularization to prevent overfitting
    layers.Dense(128, activation='relu'), # Second hidden layer with 128 neurons and ReLU activation
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),  # Third hidden layer with 64 neurons and ReLU activation
    layers.BatchNormalization(),
    layers.Dropout(0.2),
    layers.Dense(1, activation='sigmoid') # Output layer with 1 neuron and sigmoid for binary classification
])

# Compile the model
# Using Adam optimizer, Binary Crossentropy loss for binary classification, and F1-score as a metric
# F1-score is particularly useful for imbalanced datasets
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Display model summary
print("Model Summary:")
model.summary()

# Define callbacks for early stopping and learning rate reduction
early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,             # Stop if no improvement after 5 epochs
    restore_best_weights=True
)
lr_scheduler = keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.2,             # Reduce learning rate by a factor of 0.2
    patience=3,             # If no improvement for 3 epochs
    min_lr=0.0001
)

print("\nTraining the model...")
# Train the model with the resampled training data and validation on the original test set
history = model.fit(
    X_train_resampled, y_train_resampled,
    validation_data=(X_test, y_test),
    epochs=20, # Start with a reasonable number of epochs, early stopping will prevent overtrianing
    batch_size=2048, # Larger batch size for efficiency with a large dataset
    callbacks=[early_stopping, lr_scheduler],
    verbose=1
)

print("\nModel training complete.")

### 5. Building and Training the Deep Neural Network Model

Now, we'll construct a deep neural network using TensorFlow/Keras. The model will be trained on the SMOTE-resampled training data to ensure it learns effectively from both fraud and non-fraud instances. We'll use appropriate layers and activation functions for a binary classification task.

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the Deep Neural Network architecture
model = keras.Sequential([
    layers.Input(shape=(X_train_resampled.shape[1],)), # Input layer matching the number of features
    layers.Dense(256, activation='relu'), # First hidden layer with 256 neurons and ReLU activation
    layers.BatchNormalization(),          # Batch Normalization for stability and faster training
    layers.Dropout(0.3),                  # Dropout for regularization to prevent overfitting
    layers.Dense(128, activation='relu'), # Second hidden layer with 128 neurons and ReLU activation
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),  # Third hidden layer with 64 neurons and ReLU activation
    layers.BatchNormalization(),
    layers.Dropout(0.2),
    layers.Dense(1, activation='sigmoid') # Output layer with 1 neuron and sigmoid for binary classification
])

# Compile the model
# Using Adam optimizer, Binary Crossentropy loss for binary classification, and F1-score as a metric
# F1-score is particularly useful for imbalanced datasets
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Display model summary
print("Model Summary:")
model.summary()

# Define callbacks for early stopping and learning rate reduction
early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,             # Stop if no improvement after 5 epochs
    restore_best_weights=True
)
lr_scheduler = keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.2,             # Reduce learning rate by a factor of 0.2
    patience=3,             # If no improvement for 3 epochs
    min_lr=0.0001
)

print("\nTraining the model...")
# Train the model with the resampled training data and validation on the original test set
history = model.fit(
    X_train_resampled, y_train_resampled,
    validation_data=(X_test, y_test),
    epochs=5, # Start with a reasonable number of epochs, early stopping will prevent overtrianing
    batch_size=2048, # Larger batch size for efficiency with a large dataset
    callbacks=[early_stopping, lr_scheduler],
    verbose=1
)

print("\nModel training complete.")

Model Summary:

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 256)            │       311,552 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 354,561 (1.35 MB)

 Trainable params: 353,665 (1.35 MB)

 Non-trainable params: 896 (3.50 KB)

Training the model...
Epoch 1/5
1008/1008 ━━━━━━━━━━━━━━━━━━━━ 120s 116ms/step - accuracy: 0.9798 - loss: 0.0527 - precision_1: 0.9783 - recall_1: 0.9813 - val_accuracy: 0.9970 - val_loss: 0.0131 - val_precision_1: 0.7192 - val_recall_1: 0.8021 - learning_rate: 0.0010
Epoch 2/5
1008/1008 ━━━━━━━━━━━━━━━━━━━━ 142s 116ms/step - accuracy: 0.9984 - loss: 0.0054 - precision_1: 0.9978 - recall_1: 0.9990 - val_accuracy: 0.9974 - val_loss: 0.0130 - val_precision_1: 0.7629 - val_recall_1: 0.7888 - learning_rate: 0.0010
Epoch 3/5
1008/1008 ━━━━━━━━━━━━━━━━━━━━ 142s 116ms/step - accuracy: 0.9990 - loss: 0.0033 - precision_1: 0.9987 - recall_1: 0.9993 - val_accuracy: 0.9976 - val_loss: 0.0138 - val_precision_1: 0.7978 - val_recall_1: 0.7808 - learning_rate: 0.0010
Epoch 4/5
1008/1008 ━━━━━━━━━━━━━━━━━━━━ 117s 116ms/step - accuracy: 0.9993 - loss: 0.0024 - precision_1: 0.9991 - recall_1: 0.9995 - val_accuracy: 0.9979 - val_loss: 0.0137 - val_precision_1: 0.8490 - val_recall_1: 0.7682 - learning_rate: 0.0010
Epoch 5/5
1008/1008 ━━━━━━━━━━━━━━━━━━━━ 146s 120ms/step - accuracy: 0.9998 - loss: 8.6392e-04 - precision_1: 0.9996 - recall_1: 0.9999 - val_accuracy: 0.9981 - val_loss: 0.0145 - val_precision_1: 0.9100 - val_recall_1: 0.7408 - learning_rate: 2.0000e-04

Model training complete.

### 6. Model Evaluation

After training, it's important to evaluate the model's performance on the unseen test set (`X_test`, `y_test`). We will look at key metrics relevant to imbalanced classification, such as accuracy, precision, and recall.

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print("\nEvaluating the model on the test set...")
loss, accuracy, precision, recall = model.evaluate(X_test, y_test, verbose=0)

print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")
print(f"Test Precision: {precision:.4f}")
print(f"Test Recall: {recall:.4f}")

# Predict probabilities on the test set
y_pred_prob = model.predict(X_test)
# Convert probabilities to binary predictions (0 or 1) using a threshold (e.g., 0.5)
y_pred = (y_pred_prob > 0.5).astype(int)

print("\nConfusion Matrix:")
display(pd.DataFrame(confusion_matrix(y_test, y_pred), index=['Actual 0', 'Actual 1'], columns=['Predicted 0', 'Predicted 1']))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Evaluating the model on the test set...
Test Loss: 0.0130
Test Accuracy: 0.9974
Test Precision: 0.7629
Test Recall: 0.7888
8105/8105 ━━━━━━━━━━━━━━━━━━━━ 30s 4ms/step

Confusion Matrix:

          Predicted 0  Predicted 1
Actual 0       257466          368
Actual 1          317         1184

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    257834
           1       0.76      0.79      0.78      1501

    accuracy                           1.00    259335
   macro avg       0.88      0.89      0.89    259335
weighted avg       1.00      1.00      1.00    259335

### 7. Discussion and Next Steps

Based on the evaluation metrics, we can now assess the performance of our deep neural network in detecting fraudulent transactions. The precision, recall, and F1-score are particularly important for understanding how well the model identifies fraud while minimizing false positives.

**Key Observations:**
*   **Precision:** Indicates the proportion of positive identifications that were actually correct. A high precision means fewer legitimate transactions are flagged as fraudulent.
*   **Recall:** Indicates the proportion of actual positives that were correctly identified. A high recall means the model catches most fraudulent transactions.
*   **F1-Score:** The harmonic mean of precision and recall, providing a balanced measure.

Further steps could include:
*   **Hyperparameter tuning:** Adjusting the model's architecture, learning rate, dropout rates, etc.
*   **More advanced sampling techniques:** Experimenting with different SMOTE variants or other over/under-sampling methods.
*   **Feature engineering refinement:** Creating more sophisticated features that might improve model performance.
*   **Considering different model architectures:** Exploring other neural network types or ensemble methods.
*   **Threshold adjustment:** If recall or precision needs to be prioritized, the classification threshold (currently 0.5) can be adjusted.

### 4. Splitting Data and Applying SMOTE

Before training our deep neural network, we need to:
1.  **Split the data**: Separate the dataset into training and testing sets.
2.  **Apply SMOTE**: Use SMOTE (Synthetic Minority Over-sampling Technique) on the *training data only* to address the class imbalance. This will generate synthetic samples for the minority class, helping the model learn better.

In [ ]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
# Stratify by 'y' to maintain the same class distribution in both sets
# Use a test size of 20% (0.2), which is common
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42, stratify=y)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\nClass distribution in y_train before SMOTE:")
display(y_train.value_counts())
display(y_train.value_counts(normalize=True) * 100)

Shape of X_train: (1037340, 1216)
Shape of X_test: (259335, 1216)
Shape of y_train: (1037340,)
Shape of y_test: (259335,)

Class distribution in y_train before SMOTE:

is_fraud
0    1031335
1       6005
Name: count, dtype: int64

is_fraud
0    99.421116
1     0.578884
Name: proportion, dtype: float64

In [ ]:
from imblearn.over_sampling import SMOTE

print("Applying SMOTE to the training data...")

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("SMOTE application complete.")
print(f"Shape of X_train_resampled: {X_train_resampled.shape}")
print(f"Shape of y_train_resampled: {y_train_resampled.shape}")

print("\nClass distribution in y_train after SMOTE:")
display(y_train_resampled.value_counts())
display(y_train_resampled.value_counts(normalize=True) * 100)

Applying SMOTE to the training data...
SMOTE application complete.
Shape of X_train_resampled: (2062670, 1216)
Shape of y_train_resampled: (2062670,)

Class distribution in y_train after SMOTE:

is_fraud
0    1031335
1    1031335
Name: count, dtype: int64

is_fraud
0    50.0
1    50.0
Name: proportion, dtype: float64